# This file is derived from https://github.com/DeepMail/DeepMail/blob/master/docs/kubernetes/deepmail/admin-ingress.yaml

{{- $fullname := (include "deepmail.fullname" .) }}
{{ if .Values.ingress.externalIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}-ingress
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ $fullname }}
    component: admin
spec:
{{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
{{- end }}
  tls:
  - secretName: {{ $fullname }}-certificates
    hosts:
{{- range .Values.hostnames }}
    - "{{ . }}"
{{- end }}
  rules:
{{- range .Values.hostnames }}
  - host: "{{ . }}"
    http:
      paths:
      - path: "/"
        backend:
          service:
            name: {{ $fullname }}-front
            port: 
              number: 80
        pathType: ImplementationSpecific
{{- end }}
{{ end }}
